### ISSUE TITLE
cannot find ./index

### ISSUE THREAD

**Issue by alzalabany** [brunolemos/react-native-web-monorepo#44]
enviroment:
Windows 10
latest yarn, ts

git clone repo..
cd yarn && yarn workspace mobile start

bundling failed: Error: Unable to resolve module `./app.json` from `C:\workspace\react-native-web-monorepo\index.js`: The module `./app.json` could not be found from `C:\workspace\react-native-web-monorepo\index.js`. Indeed, none of these files exist:
  * `app.json`

**Comment by hosseinmd** [comment]
this error occurs when you use `react-native bundle`  
use this
`react-native bundle --platform android --dev false --entry-file packages/mobile/index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/`

`--entry-file` is defined `packages/mobile/index.js` instead of `index.js`

the bundle is not recommended.

**Comment by gko** [comment]
Try changing the path to `index` within `MainApplication.java` in `packages/mobile/android/app/src/main/java/`:
```java
@Override
protected String getJSMainModuleName() {
	return "packages/mobile/index";
}
```

**Comment by hosseinmd** [comment]
Changing then index path is not the right way, because of every platform have a different config in the index file

**Comment by gko** [comment]
@hosseinmd agree, but I also stumbled upon this problem and didn't find other solution. (react-native bundle didn't work)

**Comment by hosseinmd** [comment]
I think you have a problem in build.Gradle. Please check this.
```
project.ext.react = [
    entryFile: "packages/mobile/index.js",
    root: "../../../../",
]
```

**Comment by gko** [comment]
@hosseinmd I made a small PR fixing this issue. Tested on `android` and `ios` emulators on macOS Catalina
