### ISSUE TITLE
What is the reason of removing dependencies in root package.json

### ISSUE THREAD

**Issue by MohammadAzimi** [brunolemos/react-native-web-monorepo#75]
I'm following this repository for a while and I watched the changes, But I don't know the exact reason of doing some of them. For example:
in root `package.json` we had to add `react` and `react-native` as a dependency with the exact **version number**, some days later react-native version number changed to `"react-native": "*"`, and now there is no dependency in the root `package.json`.
What is the logic and reason behind it?

I'm trying to fix https://github.com/brunolemos/react-native-web-monorepo/issues/70 and release issues
And I think it's a good idea to enable GitHub discussion to ask some questions instead of opening issues for them like mine

**Comment by brunolemos** [comment]
when using Yarn Workspaces, we should not add dependencies to the root package.json if they are only used by the packages; we should only add them where they are directly used.

react-native in the root dependency is/was because of a bug in the react-native metro and this was/it a workaround.

I've enabled Discussions!
